POST http://localhost:3001/api/blogs
Content-Type: application/json
authorization: bearer 

{
    "title": "Yet another test!",
    "author": "Pasi Pasinen",
    "url": "http:/url.fi",
    "likes": 15,
    "userId": ""
}